allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

reviewed:
  npm:
    - arg # MIT
    - btoa-lite # MIT
    - color-convert # MIT
    - concat-map # MIT
    - diff # BSD-3-Clause
    - fast-json-stable-stringify # MIT
    - fs.realpath # ISC
    - lodash # MIT
    - lodash.get # MIT
    - lodash.set # MIT
    - lodash.uniq # MIT
    - minimist # MIT
    - mkdirp # MIT
    - source-map # BSD-3-Clause
    - sprintf-js # BSD-3-Clause
    - table # BSD-3-Clause
    - universal-user-agent # ISC
    - uri-js
    - url-template # BSD-3-Clause